name: Deploy Docs to GitHub Pages

on:
  push:
    branches: [main] # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # If you need to build your docs first, add build steps here

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs # The folder to deploy
          branch: gh-pages # The branch to deploy to
